// Generated by https://quicktype.io

export interface FilterResponse {
  id: number;
  image: string;
  nameJobTitle: string;
  initialSalaryPlanilla: number;
  finalSalaryPlanilla: number;
  initialSalaryRxH: number;
  finalSalaryRxH: number;
  location: string;
  avgRating: number;
  inUserList: number;
}
