// Generated by https://quicktype.io

export interface FilterResponse {
  id: number;
  image: string;
  nameJobTitle: string;
  initialSalary: number;
  finalSalary: number;
  location: string;
  avgRating: number;
}
