// Generated by https://quicktype.io

export interface FilterRequest {
  userId: number;
  habilities: string;
  languageIds: string;
  levelIds: string;
  nameJobTitle: string;
  userListIds: string;
  pagina: number;
}
