// Generated by https://quicktype.io

export interface FilterAndPaginationResponse {
  list: FilterResponse[];
  total: number;
}

export interface FilterResponse {
  avgRating: number;
  finalSalaryPlanilla: number;
  finalSalaryRxH: number;
  iconCoin: null | string;
  id: number;
  image: string;
  initialSalaryPlanilla: number;
  initialSalaryRxH: number;
  inUserList: null;
  location: string;
  nameJobTitle: string;
}
